/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author n11ak
 */
public class ListFileConverter extends javax.swing.JFrame {

    /**
     * Creates new form ListFileConverter
     */
    public ListFileConverter() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        addLineNumber = new javax.swing.JButton();
        convertTabButton = new javax.swing.JButton();
        messageTextField = new javax.swing.JTextField();
        addLineNumber2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        toolButtonOpen = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        toolButtonSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sourceTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        targetTextField = new javax.swing.JTextField();
        convertButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputTextArea.setColumns(20);
        inputTextArea.setRows(5);
        jScrollPane1.setViewportView(inputTextArea);

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane2.setViewportView(outputTextArea);

        addLineNumber.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        addLineNumber.setText("add Line Number:3");
        addLineNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLineNumberActionPerformed(evt);
            }
        });

        convertTabButton.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        convertTabButton.setText("Convert Tabs to 2Spaces");
        convertTabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertTabButtonActionPerformed(evt);
            }
        });

        messageTextField.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N

        addLineNumber2.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        addLineNumber2.setText("add Line Number:2");
        addLineNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLineNumber2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Input File");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Outpu File");

        jToolBar1.setRollover(true);

        toolButtonOpen.setBackground(new java.awt.Color(204, 204, 255));
        toolButtonOpen.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        toolButtonOpen.setText("Open");
        toolButtonOpen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolButtonOpen.setFocusable(false);
        toolButtonOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButtonOpen.setMargin(new java.awt.Insets(2, 4, 2, 4));
        toolButtonOpen.setMaximumSize(new java.awt.Dimension(50, 50));
        toolButtonOpen.setPreferredSize(new java.awt.Dimension(40, 40));
        toolButtonOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolButtonOpenActionPerformed(evt);
            }
        });
        jToolBar1.add(toolButtonOpen);

        jToolBar2.setRollover(true);

        toolButtonSave.setBackground(new java.awt.Color(204, 204, 255));
        toolButtonSave.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        toolButtonSave.setText("Save");
        toolButtonSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolButtonSave.setFocusable(false);
        toolButtonSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButtonSave.setMargin(new java.awt.Insets(2, 4, 2, 4));
        toolButtonSave.setMaximumSize(new java.awt.Dimension(50, 50));
        toolButtonSave.setName(""); // NOI18N
        toolButtonSave.setPreferredSize(new java.awt.Dimension(40, 40));
        toolButtonSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolButtonSaveActionPerformed(evt);
            }
        });
        jToolBar2.add(toolButtonSave);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel1.setText("source:");

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel2.setText("target:");

        convertButton.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(sourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(targetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(convertButton)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(targetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addLineNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 473, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(258, 258, 258))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addLineNumber2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(convertTabButton)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(addLineNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(convertTabButton)
                        .addGap(44, 44, 44)
                        .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addLineNumber2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLineNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLineNumberActionPerformed
        // TODO add your handling code here:
        addLineNumber(3);
    }//GEN-LAST:event_addLineNumberActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
        convertWord();
    }//GEN-LAST:event_convertButtonActionPerformed

    private void convertTabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertTabButtonActionPerformed
        // TODO add your handling code here:
        convertTab2Space();
    }//GEN-LAST:event_convertTabButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_saveAsMenuItemActionPerformed
    String openFileDir;
    String saveFileDir;
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        inputFileOpen();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void addLineNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLineNumber2ActionPerformed
        // TODO add your handling code here:
        addLineNumber(2);
    }//GEN-LAST:event_addLineNumber2ActionPerformed

    private void toolButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolButtonOpenActionPerformed
        // TODO add your handling code here:
        inputFileOpen();
    }//GEN-LAST:event_toolButtonOpenActionPerformed

    private void toolButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolButtonSaveActionPerformed

    void inputFileOpen(){
        JFileChooser filechooser;
        if(openFileDir != null){
            filechooser = new JFileChooser(new File(openFileDir));
        }else{
            filechooser = new JFileChooser();
        }

        int selected = filechooser.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION){
            File file = filechooser.getSelectedFile();
            openFileDir = file.getPath();

            inputTextArea.setText("");

            try{
                if (checkBeforeReadfile(file)){
                    BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(file), "UTF-8"));

                    String str;
                    while((str = br.readLine()) != null){
                        inputTextArea.append(str);
                        inputTextArea.append("\n");
                    }

                    br.close();
                }else{
                    System.out.println("ファイルが見つからないか開けません");
                }
            }catch(FileNotFoundException err){
                System.out.println(err);
            }catch(IOException err){
                System.out.println(err);
            }
        }
    }
    
    void outputFileSave(){
        JFileChooser filechooser;
        if(saveFileDir != null){
            filechooser = new JFileChooser(new File(saveFileDir));
        }else{
            filechooser = new JFileChooser();
        }
        filechooser.setDialogTitle("save as new file");

        int selected = filechooser.showSaveDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            saveFileDir = file.getParent();
            try {
                FileOutputStream fos = new FileOutputStream(file.getPath() + ".txt");
                OutputStreamWriter osw = new OutputStreamWriter(fos, "UTF-8");
                String allString = outputTextArea.getText();

                osw.write(allString);
                osw.close();
                fos.close();
                messageTextField.setText("File is saved as " + file.getName());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } else if (selected == JFileChooser.CANCEL_OPTION) {
            messageTextField.setText("キャンセルされました");
        } else if (selected == JFileChooser.ERROR_OPTION) {
            messageTextField.setText("エラー又は取消しがありました");
        }        
    }
    
    private static boolean checkBeforeReadfile(File file){
        if (file.exists()){
            if (file.isFile() && file.canRead()){
                return true;
        }
    }
    return false;
  }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListFileConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListFileConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListFileConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListFileConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListFileConverter().setVisible(true);
            }
        });
        
    }
    
    public void addLineNumber(int columnNumber){
        if(columnNumber < 1 || columnNumber > 9)return;
        
        String allString = inputTextArea.getText();
        outputTextArea.setText("");
        String[] processText = allString.split("\n");
            for(int i=0; i < processText.length; i++){
                processText[i] = String.format("%" + columnNumber + "d：", i+1) + processText[i] + "\n";  //the number is should be started by 1, because that's line number.
                outputTextArea.append(processText[i]);            
        }
        messageTextField.setText("Line number is inserted");
    }
    
    public void convertWord(){
        String allString = outputTextArea.getText();
        outputTextArea.setText("");
        String[] processText = allString.split("\n");
        for(int i=0; i < processText.length; i++){
            processText[i].replaceAll(sourceTextField.getText(), targetTextField.getText());
            outputTextArea.append(processText[i] + "\n");
        }
    }
    
    public void convertTab2Space(){
        String allString = outputTextArea.getText();
        outputTextArea.setText("");
        String[] processText = allString.split("\n");
        for(int i=0; i < processText.length; i++){
            outputTextArea.append(processText[i].replaceAll("\t", "  ") + "\n");
        }    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addLineNumber;
    private javax.swing.JButton addLineNumber2;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JButton convertButton;
    private javax.swing.JButton convertTabButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JTextField sourceTextField;
    private javax.swing.JTextField targetTextField;
    private javax.swing.JButton toolButtonOpen;
    private javax.swing.JButton toolButtonSave;
    // End of variables declaration//GEN-END:variables

}
